#! /bin/bash
#until [[ -f /var/lib/cloud/instance/boot-finished ]]; do
#  sleep 1
#done
sudo yum update -y
sudo yum install nmap -y
sudo amazon-linux-extras install docker -y
sudo service docker start
sudo systemctl enable docker
sudo usermod -a -G docker ec2-user
sudo yum install git -y
#sudo docker pull jenkins/jenkins:2.138
#sudo docker run --name jenkins_vuln jenkins/jenkins:2.138


## Install old go vulnerables packages

wget https://go.dev/dl/go1.19.1.linux-amd64.tar.gz
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf go1.19.1.linux-amd64.tar.gz
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile
source ~/.profile


## Install the defender 

curl -sSL --header "authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWRhbGJlc0BwYWxvYWx0b25ldHdvcmtzLmNvbSIsInJvbGUiOiJhZG1pbiIsInJvbGVQZXJtcyI6W1syNTUsMjU1LDI1NSwyNTUsMjU1LDk1XSxbMjU1LDI1NSwyNTUsMjU1LDI1NSw5NV1dLCJzZXNzaW9uVGltZW91dFNlYyI6NTY4LCJzYWFzVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlKOS5leUp6ZFdJaU9pSnRaR0ZzWW1WelFIQmhiRzloYkhSdmJtVjBkMjl5YTNNdVkyOXRJaXdpYzJWeWRtbGpaVlZ6WVdkbFQyNXNlU0k2ZEhKMVpTd2labWx5YzNSTWIyZHBiaUk2Wm1Gc2MyVXNJbkJ5YVhOdFlVbGtJam9pT1RBeU5UazVNelEwT1RjMU56VTVNell3SWl3aWFYQkJaR1J5WlhOeklqb2lNelF1TVRNNUxqWTBMakUxTUNJc0ltbHpjeUk2SW1oMGRIQnpPaTh2WVhCcE1pNXdjbWx6YldGamJHOTFaQzVwYnlJc0luSmxjM1J5YVdOMElqb3dMQ0oxYzJWeVVtOXNaVlI1Y0dWRVpYUmhhV3h6SWpwN0ltaGhjMDl1YkhsU1pXRmtRV05qWlhOeklqcG1ZV3h6Wlgwc0luVnpaWEpTYjJ4bFZIbHdaVTVoYldVaU9pSlRlWE4wWlcwZ1FXUnRhVzRpTENKcGMxTlRUMU5sYzNOcGIyNGlPblJ5ZFdVc0lteGhjM1JNYjJkcGJsUnBiV1VpT2pFM05qSTBNak0wT0RJM01ESXNJbUYxWkNJNkltaDBkSEJ6T2k4dllYQnBNaTV3Y21semJXRmpiRzkxWkM1cGJ5SXNJblZ6WlhKU2IyeGxWSGx3WlVsa0lqb3hMQ0poZFhSb0xXMWxkR2h2WkNJNklsTkJUVXd5SWl3aWMyVnNaV04wWldSRGRYTjBiMjFsY2s1aGJXVWlPaUpCVUZBeUlGQnlhWE50WVNCRGJHOTFaQ0JEZFhOMGIyMWxjaUJUZFdOalpYTnpJRXhoWWkwZ05UUXhPREUyTkRFMk56QXhPRGM1T0RBME9DSXNJbk5sYzNOcGIyNVVhVzFsYjNWMElqbzJNQ3dpZFhObGNsSnZiR1ZKWkNJNkltWXpOV001T1RnNExURm1ZVEV0TkdVM09TMWhPRFZoTFRRek1XRmxOVFZpTVRJME9DSXNJbWhoYzBSbFptVnVaR1Z5VUdWeWJXbHpjMmx2Ym5NaU9tWmhiSE5sTENKbGVIQWlPakUzTmpJME1qUTFOaklzSW1saGRDSTZNVGMyTWpReU16azJNaXdpZFhObGNtNWhiV1VpT2lKdFpHRnNZbVZ6UUhCaGJHOWhiSFJ2Ym1WMGQyOXlhM011WTI5dElpd2lkWE5sY2xKdmJHVk9ZVzFsSWpvaVUzbHpkR1Z0SUVGa2JXbHVJbjAueHRzZ1dTUlIxVXFYWC1mY2NPMFpkV2EzZGE0OWlEcklzMHhvMzlKSUN4NCIsImlzcyI6InR3aXN0bG9jayIsImV4cCI6MTc2MjQyNzU5NH0.7wvyDWmYXnl8EgQvlBmnMqX-aot86M6l4xbZhVWDPnE" -X POST https://us-east1.cloud.twistlock.com/us-2-158320372/api/v1/scripts/defender.sh | sudo bash -s -- -c "us-east1.cloud.twistlock.com" -v -m --install-host